default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tweet_clone_development
test:
  <<: *default
  database: tweet_clone_test
production:
  <<: *default
  database: tweet_clone_production
  username: tweet_clone
  password: <%= ENV['TWEET_CLONE_DATABASE_PASSWORD'] %>
